# Generated by Django 2.0.4 on 2018-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180418_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('blog', models.TextField(default='')),
                ('author', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='blog_post',
        ),
    ]
